name: Deploy Python app to server

on:
  push:
    paths:
      - "flask/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy project files to server via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "flask/*"
        target: "~"
    - name: Deploy app
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          apt install python3.12-venv -y
          cd flask
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          gunicorn -w 4 -b 0.0.0.0:3003 main:app --daemon --reload